### ISSUE TITLE
Find the number of islands.

### ISSUE THREAD

**Issue by coderAbhik** [the-moonLight0/Hactober-fest-2021#38]
Issue: A Boolean 2D matrix, find the number of islands. A group of connected 1s forms an island.

Implementation : By applying DFS on each element. In each DFS call, a component or a sub-graph is visited. We will call DFS on the next un-visited element. The number of calls to DFS gives the number of connected components.

Changes: TODO

@the-moonLight0 I am participant in hacktoberfest'21. Please assign me the above issue. Thanks.

**Comment by the-moonLight0** [comment]
go ahead

**Comment by coderAbhik** [comment]
PR has been raised for your review: 
Islands #43
