### ISSUE TITLE
Block Swap Algo for Array Rotation

### ISSUE THREAD

**Issue by rgv2417arora** [the-moonLight0/Hactober-fest-2021#46]
@the-moonLight0  I am going to implement Array Rotation with Block Swap Algo.

I want to contribute this for HacboberFest. Kindly Accept

**Comment by the-moonLight0** [comment]
go ahead

**Comment by rgv2417arora** [comment]
PR added 
https://github.com/the-moonLight0/Hactober-fest-2021/pull/58

Kindly add hatoberfest accepted label
