### ISSUE TITLE
Split the array and adding the first part to the end Solution

### ISSUE THREAD

**Issue by rgv2417arora** [the-moonLight0/Hactober-fest-2021#47]
@the-moonLight0 I want to implement the above-stated Problem.

I want to contribute this for HacboberFest. Kindly Accept

**Comment by the-moonLight0** [comment]
go ahead

**Comment by rgv2417arora** [comment]
PR added
https://github.com/the-moonLight0/Hactober-fest-2021/pull/57

Please add hactoberfest accepted label
