### ISSUE TITLE
Poor Naming  convention

### ISSUE THREAD

**Issue by the-moonLight0** [the-moonLight0/Hactober-fest-2021#50]
file link : 
 https://github.com/the-moonLight0/Hactober-fest-2021/blob/089d4d6c5c8833ef8f11fc0686a61dc68b8262e5/Solution.java
This file contains the solution to detect loops in a linked list. 
Please give this file a good and descriptive name.

**Comment by coderAbhik** [comment]
Please assign me this issue. thanks.

**Comment by rgv2417arora** [comment]
Here is the PR.
https://github.com/the-moonLight0/Hactober-fest-2021/pull/53

Kindly assign this PR to me

**Comment by the-moonLight0** [comment]
done
