### ISSUE TITLE
Invalid file type

### ISSUE THREAD

**Issue by the-moonLight0** [the-moonLight0/Hactober-fest-2021#51]
The file extension of : https://github.com/the-moonLight0/Hactober-fest-2021/blob/089d4d6c5c8833ef8f11fc0686a61dc68b8262e5/infix%20to%20prefix 
should be .java

**Comment by coderAbhik** [comment]
please assign me this issue will correct it. thanks

**Comment by coderAbhik** [comment]
PR has been raised. Please review. Thanks

Infix to prefix branch #54
